### ISSUE TITLE
Hardware Information

### ISSUE THREAD

**Issue by Lwzzzzzz** [zysong0113/SAVC#3]
Hello, I would like to evaluate if I can use this model, can you share information about the hardware you are using？

**Comment by Lwzzzzzz** [comment]
By the way, it would be better if there is corresponding training time

**Comment by zysong0113** [comment]
Hello, our experiments used one 32GB V100 GPU, and every of them could be finished in one day. CUB200 dataset is relatively small, and the fantasy method we used on it is the simplest, you can first make an attempt on it.

**Comment by Lwzzzzzz** [comment]
Thanks!
