### ISSUE TITLE
about the exact valuses on CIFAR100 and miniImageNet

### ISSUE THREAD

**Issue by learn-in-practice** [zysong0113/SAVC#5]
Thank you for your excellent work. Could you please present the exact values on CIFAR100 and miniImageNet in the Figure 4? Thank you very much.

**Comment by zysong0113** [comment]
Hello, the detailed results on CIFAR100 and miniImageNet can be found in the appendix: https://openaccess.thecvf.com/content/CVPR2023/supplemental/Song_Learning_With_Fantasy_CVPR_2023_supplemental.pdf

**Comment by hongbo-sun** [comment]
Got it. Thanks.
