### ISSUE TITLE
Why does it report an error every time when the model train to the image "White_Pelican_0081_96148. jpg" in CUB200?

### ISSUE THREAD

**Issue by ChenZhiMing66** [zysong0113/SAVC#6]
Thank you for your excellent work. But I encountered some problems during the training process, and I hope you can provide some answers. Thank you very much.
![image](https://github.com/zysong0113/SAVC/assets/55489611/0ab8bf05-91ac-41c6-8dd3-e3072d3f318a)

**Comment by zysong0113** [comment]
Hello, the code runs normally on my machine. I think you can check if there are something wrong with your CUB dataset. Good luck!

**Comment by Julesaiyy** [comment]
I have the same problem. I have tried many times in the cub200 datasets which is from https://drive.google.com/drive/folders/11LxZCQj2FRCs0JTsf_dafvTHqFn2yGSN.
